name: ui_view_laboratory
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  top_snackbar_flutter: ^3.1.0
  sliding_up_panel: ^2.0.0+1

flutter:
  uses-material-design: true
